# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circleblogapp', '0002_auto_20180323_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
